### ISSUE TITLE
Baby crying detention

### ISSUE THREAD

**Issue by jahegu** [roleoroleo/yi-hack-MStar#172]
hello,

official software includes baby crying detention. Would it be possible to add this option on MQTT alerts?

BR,

**Comment by roleoroleo** [comment]
Which model do you have?
In my model it's not available.

**Comment by jahegu** [comment]
BFUS and 9FUS

**Comment by roleoroleo** [comment]
Try the last version.

**Comment by jahegu** [comment]
Thank you very much. I'll comment as soon as any of my Baby's cry.

BR,

**Comment by roleoroleo** [comment]
I tested it with this:
https://www.youtube.com/watch?v=iVeKq9sriuA

**Comment by PieVo** [comment]
Besides the baby-cry detection, it would eventually be possible to do basic audio level-triggering since we continuously read audio in tinyalsa.

**Comment by jahegu** [comment]
I have checked several times. Native application trigger but I do not get any MQTT specific alarm. 
Movement messages arrives correctly.

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/issues/175

**Comment by jahegu** [comment]
I confirm that it worked on 0.3.3

Thank you very much for the enhacement!

**Comment by kylehase** [comment]
I just picked up a Yi 1080p Dome BFUS and loaded 0.3.5 but only got baby_crying to publish once. I'm also not receiving crying notifications in the Yi app since that one. The mic is set to on in the app and baby crying detect is enabled in both the app and web UI. What steps can I take to troubleshoot this issue? I've tried disabling RTSP audio but that made no difference. Even went as far as to try downgrading to 0.3.4, which also didn't work.

**Comment by kylehase** [comment]
It turned out to be both sensor reset duration as well as crying amplitude which caused the mqtt failure. Sensor reset duration seems to be >1min even when "alert frequency" is set to "high" in the Yi app. Also crying had to be surprisingly loud in order to trigger the alert. Unfortunately I believe these issues are within the Yi part of the firmware and likely not configurable beyond what is exposed in the Yi app.

For my use case, I'll try using an ffmpeg noise trigger from the RTSP stream instead.

**Comment by roleoroleo** [comment]
I believe your analysis is correct.
The baby crying and human detection features are not working well.
