### ISSUE TITLE
HA integration

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-MStar#351]
Please, take a look at this project:

https://github.com/roleoroleo/yi-hack_ha_integration

**Comment by foxel** [comment]
Cool :+1: 

* https://github.com/roleoroleo/yi-hack_ha_integration/blob/9d370701f728357a40ca710bbab1e796ea2e2f39/yi-hack/camera.py#L61 - suffix looks strange, shouldn't it start with an underscore?
* https://github.com/roleoroleo/yi-hack_ha_integration/blob/9d370701f728357a40ca710bbab1e796ea2e2f39/yi-hack/camera.py#L72 - should be `self._port`
* https://github.com/roleoroleo/yi-hack_ha_integration/blob/9d370701f728357a40ca710bbab1e796ea2e2f39/yi-hack/binary_sensor.py#L178-L187 - duplicate code
* https://github.com/roleoroleo/yi-hack_ha_integration/blob/9d370701f728357a40ca710bbab1e796ea2e2f39/yi-hack/config_flow.py#L57-L68 - all of these variables are local to `async_step_user` and not needed to be members of the flow instance

Since topics are configurable after the integration is configured it looks like you need to read topics at least inside `async_setup_entry` so that users don't need to remove and re-add the integration after such changes.

**Comment by roleoroleo** [comment]
Thak you for your notes.
I'm taking my first steps in ha programming and I need guidance.

**Comment by roleoroleo** [comment]
Done.
About the last step, I need to study it.

**Comment by roleoroleo** [comment]
I fixed the last step but I have a weird problem after this change.
When the wizard completes, ha doesn't ask the destination area for the new entities.
I have to set it later.

**Comment by divemasterjm** [comment]
i ha to comment AI HUMAN and SOUND in init_py cause integration throw an error with this entities. after comment worked ok

**Comment by roleoroleo** [comment]
What's your model?
mstar, allwinner or allwinner-v2?

**Comment by divemasterjm** [comment]
mstar

**Comment by roleoroleo** [comment]
Ok, fixed AI HUMAN and SOUND.
Thanks.

**Comment by roleoroleo** [comment]
What do you mean with "i miss binary_sensor to activate/desactivate motion events"?

**Comment by divemasterjm** [comment]
as per your integration you can have only few sensor, will be nice to have as most as you can just for setting up automations, i mean for binary_sensor for activation of motion events for having a sensor to activate or deactivate motion enevts just to for example setup an automation to record and have snapshots on/off

**Comment by foxel** [comment]
@divemasterjm the thing you are asking for should be performed with one binary sensor. In HA you can trigger automation on both events where it goes from no motion to motion detected and vice-versa

**Comment by divemasterjm** [comment]
@foxel i know but i want to deactivate motion detection based on state if for example alarm is amerd home, night, away, therefore i only have snapshot or movie when this setting is on

**Comment by roleoroleo** [comment]
Sorry but I don't understand.
Could you explain me better?

**Comment by divemasterjm** [comment]
i want to have ftp uploads of  images or videos que i turn switch ftp updload ON
this why i ask for having more switches in the integration to control camera

FTP Upload | Enable/disable upload of recorded events to a FTP service.
-- | --
