### ISSUE TITLE
Problem with overwriting files on ftp upload without directory tree

### ISSUE THREAD

**Issue by Klay4** [roleoroleo/yi-hack-MStar#479]
When you enable the upload of the recordings to FTP, if you don’t enable the directory tree then the FTP server will only keep the recordings for one hour, because each time it will overwrite the previous files since the file name format is MinuteSeconds60.mp4

Exemple:
```
00M00S60.mp4
...
03M00S60.mp4
04M00S60.mp4
...
59M00S60.mp4
```

**Comment by denven** [comment]
I guess it's not the issue of an FTP server, it is because the files you upload contain the same file names as some you've already uploaded. Due to the naming rule of a video record file, I guess you have to upload files by separating their directories to avoid overwrite behavior and files lost. The suggestion is to upload your files by directories named by the dates instead of by files to the same directory. Otherwise, you can only keep the latest files uploaded and 60 files at most on your FTP server.  


> When you enable the upload of the recordings to FTP, if you don’t enable the directory tree then the FTP server will only keep the recordings for one hour, because each time it will overwrite the previous files since the file name format is MinuteSeconds60.mp4
> 
> Exemple:
> 
> ```
> 00M00S60.mp4
> ...
> 03M00S60.mp4
> 04M00S60.mp4
> ...
> 59M00S60.mp4
> ```
